apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gcp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Adman-Corp/multicloud-k8s-failover.git
    targetRevision: main
    path: gitops/platform/gcp/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
